apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-dev
  labels:
    app: nginx               # Add a label for better identification
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command:
        - /bin/sh
        - -c
        - echo 'Hello I am Dev-Deployment with ngix' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32300    # NodePort range: 30000-32767

